//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class city
    {
        public int city_id { get; set; }
        public string city_name { get; set; }
        public string city_url { get; set; }
        public int state_id { get; set; }
        public string region_id { get; set; }
    }
}
